[package]
name = "slowshell-widgets"
version.workspace = true
edition = "2024"

[dependencies]
iced.workspace = true
iced_layershell.workspace = true
slowshell-core = { path = "../core" }
slowshell-commons = { path = "../commons" }
slowshell-config = { path = "../config" }
freedesktop-icons.workspace = true
