[package]
name = "slowshell-services"
version = "0.1.0"
edition = "2024"

[dependencies]
slowshell-commons = { path = "../commons" }

miette.workspace = true
libc.workspace = true
tokio.workspace = true
zbus.workspace = true
futures-util.workspace = true
system-tray.workspace = true
sysinfo = { version = "0.37", default-features = false, features = ["system", "component", "network"] }