[package]
name = "slowshell-components"
version = "0.1.0"
edition = "2024"

[dependencies]
slowshell-core = { path = "../core" }
slowshell-widgets = { path = "../widgets" }
slowshell-commons = { path = "../commons" }
slowshell-config = { path = "../config" }
slowshell-registry = { path = "../registry" }
slowshell-compositor = { path = "../compositor" }
slowshell-services = { path = "../services" }

chrono.workspace = true
miette.workspace = true
iced.workspace = true
iced_layershell.workspace = true
nix.workspace = true
tokio.workspace = true
freedesktop-desktop-entry.workspace = true
