[package]
name = "slowshell-spotlight"
version = "0.1.0"
edition = "2024"

[dependencies]
iced.workspace = true
iced_layershell.workspace = true
slowshell-core = { path = "../core" }
slowshell-config = { path = "../config" }
slowshell-commons = { path = "../commons" }
slowshell-desktop = { path = "../desktop" }
slowshell-widgets = { path = "../widgets" }
slowshell-registry = { path = "../registry" }
miette.workspace = true
serde.workspace = true
libc.workspace = true
