[package]
name = "slowshell-panels"
version = "0.1.0"
edition = "2024"

[dependencies]
iced.workspace = true
iced_layershell.workspace = true
slowshell-core = { path = "../core" }
slowshell-commons = { path = "../commons" }
slowshell-config = { path = "../config" }
slowshell-desktop = { path = "../desktop" }
slowshell-components = { path = "../components" }
anyhow.workspace = true
