[package]
name = "slowshell-panels"
version.workspace = true
edition = "2024"

[dependencies]
iced.workspace = true
iced_anim.workspace = true
iced_layershell.workspace = true
slowshell-core = { path = "../core" }
slowshell-commons = { path = "../commons" }
slowshell-config = { path = "../config" }
slowshell-desktop = { path = "../desktop" }
slowshell-components = { path = "../components", default-features = false }
slowshell-registry = { path = "../registry" }
miette.workspace = true
kdl.workspace = true
