[package]
name = "slowshell"
version = "0.0.1"
edition = "2024"

[dependencies]
slowshell-core = { path = "../core" }
slowshell-config = { path = "../config" }
slowshell-desktop = { path = "../desktop" }
slowshell-registry = { path = "../registry" }
slowshell-compositor = { path = "../compositor" }
slowshell-notifications = { path = "../notifications" }
slowshell-panels = { path = "../panels" }
slowshell-spotlight = { path = "../spotlight" }
slowshell-ipc = { path = "../ipc" }
slowshell-widgets = { path = "../widgets" }
slowshell-components = { path = "../components" }
slowshell-menus = { path = "../menus" }
slowshell-popups = { path = "../popups" }
slowshell-background = { path = "../background" }
slowshell-plugin-host = { path = "../plugin-host" }

nix.workspace = true
libc.workspace = true
miette.workspace = true
iced.workspace = true
iced_layershell.workspace = true
futures-channel.workspace = true
futures-lite = "2"
clap.workspace = true
