[package]
name = "slowshell-registry"
version = "0.1.0"
edition = "2024"

[dependencies]
slowshell-core = { path = "../core" }
slowshell-config = { path = "../config" }
slowshell-desktop = { path = "../desktop" }
slowshell-widgets = { path = "../widgets" }

serde.workspace = true
miette.workspace = true
iced.workspace = true
