[package]
name = "slowshell-background"
version = "0.1.0"
edition = "2024"

[dependencies]
slowshell-core = { path = "../core" }
slowshell-config = { path = "../config" }
slowshell-desktop = { path = "../desktop" }
slowshell-registry = { path = "../registry" }
slowshell-widgets = { path = "../widgets" }

iced_layershell.workspace = true
iced.workspace = true
image.workspace = true
anyhow.workspace = true
serde.workspace = true
