[package]
name = "slowshell-popups"
version = "0.1.0"
edition = "2024"

[dependencies]
slowshell-core = { path = "../core" }
slowshell-commons = { path = "../commons" }
slowshell-widgets = { path = "../widgets" }
slowshell-config = { path = "../config" }
slowshell-desktop = { path = "../desktop" }
slowshell-registry = { path = "../registry" }

iced.workspace = true
iced_layershell.workspace = true
miette.workspace = true
